version: '3'
services:
  web:
    image: nginx:latest    
    container_name: web    
    depends_on:
      - php
    ports:
      - 8080:80
      - 443:443
    volumes:
      - $DIRECORY_FOR_VOLUME/nginx/www:/www
      - $DIRECORY_FOR_VOLUME/nginx/sites:/etc/nginx/conf.d/    
    restart: unless-stopped
    network_mode: host

  php: #Listening on port 9000
    image: php:7-fpm
    container_name: php
    restart: always
    volumes:
        - $DIRECORY_FOR_VOLUME/nginx/www:/www
    restart: unless-stopped
    network_mode: host
