version: '3.7'
services:
  traccar:
    image: traccar/traccar:4.12-ubuntu
    container_name: traccar
    hostname: traccar
    ports:
      - 8082:8082
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
    network_mode: host
    volumes:
      - /var/log/traccar:/opt/traccar/logs
      - ./conf:/opt/traccar/conf
      - ./data:/opt/traccar/data
    restart: unless-stopped
