version: "3.7"

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/homelab/:/srv
      - ./database:/database
      - ./config:/config
    ports:
      - 8090:80
    restart: unless-stopped
