version: '3.7'
services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    depends_on:
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config    
    environment:
      - TZ=Europe/Budapest
    restart: unless-stopped
    network_mode: host
    privileged: true
