version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    hostname: mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./data:/mosquitto/data
      - /var/log/mosquitto:/mosquitto/logs
      - /var/run:/var/run
      - ./conf:/mosquitto/config
    restart: unless-stopped
    network_mode: host
