version: "3.7"

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud
    ports:
      - 8888:80/tcp
      - 8888:80/udp
    volumes:
      - /mnt/homelab/nextcloud:/var/www/html
    restart: always