version: "3.3"

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud
    depends_on:
      - db    
    ports:
      - 8888:80/tcp
      - 8888:80/udp
    volumes:
      - ./nextcloud:/var/www/html
    restart: always
    network_mode: host