version: '3.7'
services: 
  cron:
    build: ./build
    container_name: cron
    hostname: cron
    volumes:
      ## If you have schedule, put it itnto the cron.d with a right cron format      
      ## for example call a website every minute: * * * * *   root  curl https://www.redman.hu
      ## And put every output to the /out to sse the result
      - ./cron.d:/etc/cron.d
      - ./out:/out      
    restart: unless-stopped    
