version: '3.7'
services: 
  cron:
    build: ./build
    container_name: cron
    hostname: cron
    volumes:
      - /etc/cron.d:/etc/cron.d
      - /etc/cron.daily:/etc/cron.daily
      - /etc/cron.hourly:/etc/cron.hourly
      - /etc/cron.monthly:/etc/cron.monthly
      - /etc/cron.weekly:/etc/cron.weekly     
    restart: unless-stopped    
