version: '3.7'
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    hostname: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=redman #optional
      - PASS=transmission #optional
      #- WHITELIST=iplist #optional
      #- HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ./config:/config
      - /mnt/homelab/downloads:/downloads/complete
      - /mnt/homelab/incomplete_downloads:/downloads/incomplete
      - /mnt/homelab/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped